### PR TITLE
Added Array/4_Two_sum

### PR DESCRIPTION
**Pull request by MinalGhate**
Added java solution for array topic question no.4 two sum
issue #33

### CODE REVIEW

**Comment by Pratham2301** [comment]
You made a PR from your branch to main branch of DSA Repo
Make PR to your branch of DSA Repo

**Comment by MinalGhate** [comment]
> You made a PR from your branch to main branch of DSA Repo Make PR to your branch of DSA Repo

Do I have to make PR to MinalGhate:main from MinalGhate:MinalGhate?
But then that changes will be in my forked repository only, how will you know that then?

**Comment by MinalGhate** [comment]
Or Do I have to first merge my MinalGhate branch with main, and then make a PR to Git-for-Geeks:main from MinalGhate:main?
@Pratham2301

**Comment by MinalGhate** [comment]
> You made a PR from your branch to main branch of DSA Repo Make PR to your branch of DSA Repo

Done 👍

**Pull request closed without merging**
